### ISSUE TITLE
GitHub action fails - /entrypoint.sh: line 12: /github/workspace/node_modules/.bin/eslint: not found

### ISSUE THREAD

**Issue by shamprasadrh** [reviewdog/action-eslint#56] opened 2020-10-28 12:14 UTC
since yesterday the action is failing with below error. ESLINT is in dependancies.  Other action action with npm install works fine. 

/usr/bin/docker run --name e5c352e88ee65616d499fb5ca9b1a6af96747_8229d6 --label 1e5c35 --workdir /github/workspace --rm -e github_token -e INPUT_REPORTER -e INPUT_ESLINT_FLAGS -e INPUT_GITHUB_TOKEN -e INPUT_LEVEL -e INPUT_FILTER_MODE -e INPUT_FAIL_ON_ERROR -e INPUT_REVIEWDOG_FLAGS -e INPUT_WORKDIR -e INPUT_TOOL_NAME -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/xxxxxx/xxxxx":"/github/workspace" 1e5c35:2e88ee65616d499fb5ca9b1a6af96747
npm WARN tarball tarball data for oneWeirMobile@git+ssh://git@github.com/xxxxxx/xxxxxxx.git#667b6a8ecf8b82bb313a8fb136f8bb990b808f53 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for oneWeirMobile@git+ssh://git@github.com/xxxxxx/xxxxxxx.git#667b6a8ecf8b82bb313a8fb136f8bb990b808f53 (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall spawn bash
npm ERR! path bash
npm ERR! errno -2
npm ERR! enoent spawn bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-10-28T12_04_55_439Z-debug.log
/entrypoint.sh: line 12: /github/workspace/node_modules/.bin/eslint: not found
/entrypoint.sh: line 14: /github/workspace/node_modules/.bin/eslint: not found
reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token

**Comment by hazcod** [comment] 2020-12-29 08:40
Same for me.

**Comment by haya14busa** [comment] 2021-02-07 12:52
I'm guessing it should be fixed by  #72 now.

**Comment by jsoref** [comment] 2021-04-06 13:51
@haya14busa: I explicitly tried v1.12.1 a bunch of times for netdata (see above) and it failed each time.

**Comment by haya14busa** [comment] 2021-05-04 15:59
Closed as obsolete. It should be actually fixed by #72 in the above comment.
Please reopen if it's not.

**Closed** 2021-05-04 15:58 UTC

**Comment by jsoref** [comment] 2021-05-04 16:18
@haya14busa: how do you figure? https://github.com/netdata/netdata/runs/2275280019 is a run specifically pinning 1.12.1 which is after 1.12.0 https://github.com/reviewdog/action-eslint/pull/72#issuecomment-774668787 and it definitely failed the same way.

You can see that I tried explicitly using 1.12.1 on a whole bunch of branches/PRs and none of them worked.

**Comment by haya14busa** [comment] 2021-05-04 16:27
I cannot find eslint in the repo. https://github.com/netdata/netdata/blob/master/package.json
Users need to install eslint [as described in the readme](https://github.com/reviewdog/action-eslint#example-usage).


As for the original report in this bug, ESLINT is in dependencies and the failure is caused by npm install.
